// DOM要素
const _byId = (id) => document.getElementById(id);

export const Elm = {
  keyword: _byId('keyword'),
  clearBtn: _byId('clearBtn'),
  connectBtn: _byId('connectBtn'),
  leaveBtn: _byId('leaveBtn'),
  statusText: _byId('statusText'),
  timer: _byId('timer'),
  statusText2: _byId('statusText2'),
  timer2: _byId('timer2'),
  localVideo: _byId('localVideo'),
  remoteVideo: _byId('remoteVideo'),
  localAA: _byId('localAA'),
  remoteAA: _byId('remoteAA'),
  canvas: _byId('canvas'),
  videoSelect: _byId('videoSelect'),
  audioSelect: _byId('audioSelect'),
  refreshDevices: _byId('refreshDevices'),
  deviceBtn: _byId('deviceBtn'),
  mobileDeviceBtn: _byId('mobileDeviceBtn'),
  deviceDialog: _byId('deviceDialog'),
  closeDialog: _byId('closeDialog'),
  videoSelectDialog: _byId('videoSelectDialog'),
  audioSelectDialog: _byId('audioSelectDialog'),
  refreshDevicesDialog: _byId('refreshDevicesDialog'),
  applyDevices: _byId('applyDevices'),
  helpBtn: _byId('helpBtn'),
  helpDialog: _byId('helpDialog'),
  closeHelpDialog: _byId('closeHelpDialog'),
  mobileHelpBtn: _byId('mobileHelpBtn'),
  container: _byId('container'),
  title: _byId('title'),
  controls: _byId('controls'),
  desktopStatus: _byId('desktopStatus'),
  chatArea: _byId('chatArea'),
  mobileStatus: _byId('mobileStatus'),
  remoteTitle: _byId('remoteTitle'),
  localTitle: _byId('localTitle'),
  viewport: _byId('viewport')
};
